& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'prepare_normalize.Name' = 'prepare_normalize'
'prepare_resample.Name' = 'prepare_resample'
'GroupBox1.Name' = 'GroupBox1'
'OpenFileDialog2.Name' = 'OpenFileDialog2'
'prepare_lufs.Name' = 'prepare_lufs'
'Button1.Name' = 'Button1'
'prepare_rebit.Name' = 'prepare_rebit'
'prepare_fileList.Name' = 'prepare_fileList'
'ComboBox1.Name' = 'ComboBox1'
'OpenFileDialog1.Name' = 'OpenFileDialog1'
'CheckBox2.Name' = 'CheckBox2'
'GroupBox4.Name' = 'GroupBox4'
'ListBox1.Name' = 'ListBox1'
'OpenFileDialog2.TrayLocation' = New-Object -TypeName System.Drawing.Point -ArgumentList @(17, 17)
'GroupBox3.Name' = 'GroupBox3'
'restore_defaults.Name' = 'restore_defaults'
'Label2.Name' = 'Label2'
'Label1.Name' = 'Label1'
'prepare_tp.Name' = 'prepare_tp'
'prepare_prefix.Name' = 'prepare_prefix'
'prepare_bd.Name' = 'prepare_bd'
'prepare_mixdown.Name' = 'prepare_mixdown'
'OpenFileDialog1.TrayLocation' = New-Object -TypeName System.Drawing.Point -ArgumentList @(17, 17)
'$this.Name' = 'prepare_Form'
'prepare_addToCue.Name' = 'prepare_addToCue'
'prepare_open.Name' = 'prepare_open'
'CheckBox1.Name' = 'CheckBox1'
'prepare_mixdown_v.Name' = 'prepare_mixdown_v'
'prepare_sr.Name' = 'prepare_sr'
'GroupBox2.Name' = 'GroupBox2'
'GroupBox5.Name' = 'GroupBox5'
'Label3.Name' = 'Label3'
'TextBox1.Name' = 'TextBox1'
'delete_list.Name' = 'delete_list'
}
}